# -*- coding: utf-8 -*-
"""Assignment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-5nQYWQcPh8qnEEI0FUMilI0Jmxx1Ipq

# Pattern 1
"""

n = int(input())
for i in range(0,n+1):
  for j in range(0,n-i):
    print('5',end ='')
  print()

"""# Pattern 2 """

n = int(input())
for i in range(n,0,-1):
  for j in range(0,i+1):
    print(j,end ='')
  print()

"""# Pattern 3

"""

row_num=1
row=1
while row<=5:
    col_num=row_num
    for col in range(0,row):
        print(col_num,end=' ')
    print(end='\n')
        
    row_num+=2
    row+=1

"""# Pattern 4


"""

row=1

while row<=5:
    col=row
    while col>=1:
        print(col,end=' ')
        col-=1
    print(end='\n')
    
    row+=1

"""#Pattern 5

"""

row=1
num=0
while row<5:
    col=row
    num+=row
    while col>=1:
        print(num,end=' ')
        col-=1
        num-=1
    print(end='\n')
    num+=row
    
    row+=1

"""#Pattern 6

"""

n = 7
for i in range(1, n+1): 
    num = 1
    for j in range(1, i+1): 
        print(' ', num, sep='', end='')
        num = num * (i - j) // j 

    print()

"""#Pattern 7

"""

rows = 5
for i in range(1, rows + 1):
    for j in range(1, rows + 1):
        if j <= i:
            print(i, end=' ')
        else:
            print(j, end=' ')
    print()

"""#Pattern 8

"""

rows = 8
for i in range(1, rows + 1):
    for j in range(1, i + 1):
        sqr = i * j
        print(i * j, end='  ')
    print()

"""#Pattern 9

"""

k=6
z=1

print("\n")
while k>=1:
    m=k
    zz=z
    print("\t",end=' ')
    while z>=1:
        print(' ',end=' ')
        z-=1
    
    while m>=1:
        
        print("*",end='  ')
        m-=1
        
    print(end='\n')
    
    k-=1
    z=zz+1

"""# Pattern 10


"""

k=1
z=6

print("\n")
while k<=8:
    m=k

    zz=z
    print("\t",end='')
    while z>=0:
        print(end=' ')
        z-=1
    
    while m>1:
        
        print("*",end='  ')
        m-=1
        
    print(end='\n')
    
    k+=1
    z=zz-1

"""#Pattern 11


"""

k=1
z=6

print("\n")
while k<=8:
    m=k

    zz=z
    print("\t",end=' ')
  
    
    while m>2:
        
        print("*",end='  ')
        m-=1
        
    print(end='\n')
    
    k+=1
    z=zz-1
    
k=6    
z=1

k=6
z=1

print("\n")
while k>=1:
    m=k
    zz=z
    print("\t",end=' ')
    
    
    while m>=1:
        
        print("*",end='  ')
        m-=1
        
    print(end='\n')
    
    k-=1
    z=zz+1

"""#Pattern 12

"""

row=1
while row<=9:
    if row<=5:
        col=row
        temp=row
        while col>=1:
            print('* ',end='')
            col-=1
        if temp==5:
            print()
            for j in range(0,4):
                print("* ",end='')
    else:
        col=9-row
        while col>=1:
            print("* ",end='')
            col-=1
    print()
    row+=1

"""# Pattern 13

"""

row=5
while row>=1:
    col=row-1
    while col>=1:
        print('  ',end='')
        col-=1
    stars=5-(row-1)
    while stars>=1:
        print("* ",end='')
        stars-=1
    print()
    row-=1
row=4
while row>=1:
    col=4-row+1
    while col>=1:
        print('  ',end='')
        col-=1
    stars=row
    while stars>=1:
        print("*",end=' ')
        stars-=1
    print()
    row-=1

"""#Pattern 14

"""

k=5
z=1

print("\n")
while k>=1:
    m=k
    zz=z
    print("\t",end='')
    while z>=1:
        print('',end=' ')
        z-=1
    
    while m>=1:
        
        print("*",end=' ')
        m-=1
        
    print()
    
    k-=1
    z=zz+1
k=2
z=6

while k<=6:
    m=k

    zz=z
    print("     ",end=' ')
    while z>=0:
        print(' ',end='')
        z-=1
      
    while m>1:
        
        print("*",end=' ')
        m-=1
        
    print(end='\n')
    
    k+=1
    z=zz-1

"""#Pattern 15

"""

row = 14
print("*" * row, end="\n")
i = (row // 2)
i-=1
j = 2
while i != 0:
    while j <= (row - 2):
        print("*" * i, end="")
        print("_" * j, end="")
        print("*" * i, end="\n")
        i = i - 1
        j = j + 2